/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_vehicle_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* ocp_vehicle_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[25])->(o0[5],o1[5x5],o2[5x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=1.5560000000000000e+00;
  a3=arg[0]? arg[0][3] : 0;
  a4=tan(a3);
  a4=(a2*a4);
  a5=3.0019999999999998e+00;
  a4=(a4/a5);
  a5=atan(a4);
  a6=(a1+a5);
  a7=cos(a6);
  a8=(a0*a7);
  if (res[0]!=0) res[0][0]=a8;
  a1=(a1+a5);
  a8=sin(a1);
  a9=(a0*a8);
  if (res[0]!=0) res[0][1]=a9;
  a9=sin(a5);
  a10=(a0*a9);
  a10=(a10/a2);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][4]=a10;
  a10=arg[1]? arg[1][4] : 0;
  a11=(a7*a10);
  a12=sin(a6);
  a13=arg[1]? arg[1][2] : 0;
  a14=3.3311125916055967e-01;
  a15=arg[1]? arg[1][3] : 0;
  a16=cos(a3);
  a16=casadi_sq(a16);
  a15=(a15/a16);
  a15=(a2*a15);
  a15=(a14*a15);
  a17=1.;
  a18=casadi_sq(a4);
  a18=(a17+a18);
  a15=(a15/a18);
  a19=(a13+a15);
  a19=(a12*a19);
  a19=(a0*a19);
  a11=(a11-a19);
  if (res[1]!=0) res[1][0]=a11;
  a11=(a8*a10);
  a19=cos(a1);
  a13=(a13+a15);
  a13=(a19*a13);
  a13=(a0*a13);
  a11=(a11+a13);
  if (res[1]!=0) res[1][1]=a11;
  a11=6.4267352185089976e-01;
  a10=(a9*a10);
  a13=cos(a5);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  a10=(a11*a10);
  if (res[1]!=0) res[1][2]=a10;
  a10=0.;
  if (res[1]!=0) res[1][3]=a10;
  if (res[1]!=0) res[1][4]=a10;
  a15=arg[1]? arg[1][9] : 0;
  a20=(a7*a15);
  a21=arg[1]? arg[1][7] : 0;
  a22=arg[1]? arg[1][8] : 0;
  a22=(a22/a16);
  a22=(a2*a22);
  a22=(a14*a22);
  a22=(a22/a18);
  a23=(a21+a22);
  a23=(a12*a23);
  a23=(a0*a23);
  a20=(a20-a23);
  if (res[1]!=0) res[1][5]=a20;
  a20=(a8*a15);
  a21=(a21+a22);
  a21=(a19*a21);
  a21=(a0*a21);
  a20=(a20+a21);
  if (res[1]!=0) res[1][6]=a20;
  a15=(a9*a15);
  a22=(a13*a22);
  a22=(a0*a22);
  a15=(a15+a22);
  a15=(a11*a15);
  if (res[1]!=0) res[1][7]=a15;
  if (res[1]!=0) res[1][8]=a10;
  if (res[1]!=0) res[1][9]=a10;
  a15=arg[1]? arg[1][14] : 0;
  a22=(a7*a15);
  a20=arg[1]? arg[1][12] : 0;
  a21=arg[1]? arg[1][13] : 0;
  a21=(a21/a16);
  a21=(a2*a21);
  a21=(a14*a21);
  a21=(a21/a18);
  a23=(a20+a21);
  a23=(a12*a23);
  a23=(a0*a23);
  a22=(a22-a23);
  if (res[1]!=0) res[1][10]=a22;
  a22=(a8*a15);
  a20=(a20+a21);
  a20=(a19*a20);
  a20=(a0*a20);
  a22=(a22+a20);
  if (res[1]!=0) res[1][11]=a22;
  a15=(a9*a15);
  a21=(a13*a21);
  a21=(a0*a21);
  a15=(a15+a21);
  a15=(a11*a15);
  if (res[1]!=0) res[1][12]=a15;
  if (res[1]!=0) res[1][13]=a10;
  if (res[1]!=0) res[1][14]=a10;
  a15=arg[1]? arg[1][19] : 0;
  a21=(a7*a15);
  a22=arg[1]? arg[1][17] : 0;
  a20=arg[1]? arg[1][18] : 0;
  a20=(a20/a16);
  a20=(a2*a20);
  a20=(a14*a20);
  a20=(a20/a18);
  a23=(a22+a20);
  a23=(a12*a23);
  a23=(a0*a23);
  a21=(a21-a23);
  if (res[1]!=0) res[1][15]=a21;
  a21=(a8*a15);
  a22=(a22+a20);
  a22=(a19*a22);
  a22=(a0*a22);
  a21=(a21+a22);
  if (res[1]!=0) res[1][16]=a21;
  a15=(a9*a15);
  a20=(a13*a20);
  a20=(a0*a20);
  a15=(a15+a20);
  a15=(a11*a15);
  if (res[1]!=0) res[1][17]=a15;
  if (res[1]!=0) res[1][18]=a10;
  if (res[1]!=0) res[1][19]=a10;
  a15=arg[1]? arg[1][24] : 0;
  a20=(a7*a15);
  a21=arg[1]? arg[1][22] : 0;
  a22=arg[1]? arg[1][23] : 0;
  a22=(a22/a16);
  a22=(a2*a22);
  a22=(a14*a22);
  a22=(a22/a18);
  a18=(a21+a22);
  a12=(a12*a18);
  a12=(a0*a12);
  a20=(a20-a12);
  if (res[1]!=0) res[1][20]=a20;
  a20=(a8*a15);
  a21=(a21+a22);
  a19=(a19*a21);
  a19=(a0*a19);
  a20=(a20+a19);
  if (res[1]!=0) res[1][21]=a20;
  a15=(a9*a15);
  a13=(a13*a22);
  a13=(a0*a13);
  a15=(a15+a13);
  a15=(a11*a15);
  if (res[1]!=0) res[1][22]=a15;
  if (res[1]!=0) res[1][23]=a10;
  if (res[1]!=0) res[1][24]=a10;
  a15=arg[2]? arg[2][4] : 0;
  a13=(a7*a15);
  a6=sin(a6);
  a22=arg[2]? arg[2][2] : 0;
  a20=arg[2]? arg[2][3] : 0;
  a3=cos(a3);
  a3=casadi_sq(a3);
  a20=(a20/a3);
  a20=(a2*a20);
  a20=(a14*a20);
  a4=casadi_sq(a4);
  a4=(a17+a4);
  a20=(a20/a4);
  a19=(a22+a20);
  a19=(a6*a19);
  a19=(a0*a19);
  a13=(a13-a19);
  if (res[2]!=0) res[2][0]=a13;
  a13=(a8*a15);
  a1=cos(a1);
  a22=(a22+a20);
  a22=(a1*a22);
  a22=(a0*a22);
  a13=(a13+a22);
  if (res[2]!=0) res[2][1]=a13;
  a15=(a9*a15);
  a5=cos(a5);
  a20=(a5*a20);
  a20=(a0*a20);
  a15=(a15+a20);
  a15=(a11*a15);
  if (res[2]!=0) res[2][2]=a15;
  if (res[2]!=0) res[2][3]=a17;
  if (res[2]!=0) res[2][4]=a10;
  a15=arg[2]? arg[2][9] : 0;
  a7=(a7*a15);
  a20=arg[2]? arg[2][7] : 0;
  a13=arg[2]? arg[2][8] : 0;
  a13=(a13/a3);
  a2=(a2*a13);
  a14=(a14*a2);
  a14=(a14/a4);
  a4=(a20+a14);
  a6=(a6*a4);
  a6=(a0*a6);
  a7=(a7-a6);
  if (res[2]!=0) res[2][5]=a7;
  a8=(a8*a15);
  a20=(a20+a14);
  a1=(a1*a20);
  a1=(a0*a1);
  a8=(a8+a1);
  if (res[2]!=0) res[2][6]=a8;
  a9=(a9*a15);
  a5=(a5*a14);
  a0=(a0*a5);
  a9=(a9+a0);
  a11=(a11*a9);
  if (res[2]!=0) res[2][7]=a11;
  if (res[2]!=0) res[2][8]=a10;
  if (res[2]!=0) res[2][9]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_vehicle_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_vehicle_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_vehicle_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_vehicle_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_vehicle_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_vehicle_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_vehicle_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_vehicle_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_vehicle_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ocp_vehicle_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ocp_vehicle_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_vehicle_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_vehicle_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_vehicle_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_vehicle_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_vehicle_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
